name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libz-dev
        # Additional steps for installing CUDA Toolkit if needed

    - name: Set up CMake
      run: |
        sudo apt-get install -y cmake
        cmake --version

    - name: Install CUDA Toolkit if needed
      if: matrix.compiler == 'gcc-9'
      run: |
        # Download and install CUDA Toolkit
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
        sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
        sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
        sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
        sudo apt-get update
        sudo apt-get -y install cuda
        sudo apt-get -y install nvidia-cuda-toolkit

        # Set CUDA Toolkit root directory
        export CUDAToolkit_ROOT=/usr/local/cuda
        export CUDAToolkit_ROOT=/usr/local/cuda/bin:$CUDAToolkit_ROOT

    - name: Configure and build project
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCUDAToolkit_ROOT=${CUDAToolkit_ROOT}
        make

    - name: Run tests
      run: |
        ./varigraph -h

