name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:12.4.1-devel-ubuntu20.04

    steps:
    - name: Set timezone to avoid interactive prompt
      run: |
        export DEBIAN_FRONTEND=noninteractive
        ln -fs /usr/share/zoneinfo/UTC /etc/localtime
        apt-get update
        apt-get install -y tzdata
        dpkg-reconfigure --frontend noninteractive tzdata

    - name: Install Git 2.18+
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y software-properties-common
        add-apt-repository ppa:git-core/ppa -y
        apt-get update
        apt-get install -y git
        git --version

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install additional dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y libz-dev libtinfo6

    - name: Install CMake 3.24+
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y wget
        wget https://github.com/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-linux-x86_64.sh
        chmod +x cmake-3.26.4-linux-x86_64.sh
        ./cmake-3.26.4-linux-x86_64.sh --skip-license --prefix=/usr/local
        cmake --version

    - name: Configure and build project
      run: |
        cmake . -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCUDA_ARCHITECTURES=75 -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc
        make
