jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:12.4.1-devel-ubuntu20.04

    steps:
    - name: Install Git 2.18+
      run: |
        apt-get update
        apt-get install -y software-properties-common
        add-apt-repository ppa:git-core/ppa -y
        apt-get update
        apt-get install -y git
        git --version

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install additional dependencies
      run: |
        apt-get update
        apt-get install -y libz-dev libtinfo6 cmake

    - name: Configure and build project
      run: |
        cmake . -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCUDA_ARCHITECTURES=75 -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc
        make
